Repository DeepLink-org/deeplink.framework, pull requests merged in 2023-10, with the labels that each got.

#318 fix bind error of erfinv: diopiErf -> diopiErfinv
  dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
Labels: bug

#301 (lljbash) CMake 优化
  dipu/CMakeLists.txt
  dipu/QuickStart.md
  dipu/scripts/ci/ascend/ci_ascend_env.sh
  dipu/scripts/ci/camb/ci_camb_env.sh
  dipu/scripts/ci/camb/ci_camb_script.sh
  dipu/scripts/ci/nv/ci_nv_env.sh
  dipu/scripts/ci/nv/ci_nv_script.sh
  dipu/scripts/ci/topsrider/ci_topsrider_env.sh
  dipu/setup.py
  dipu/template_build_sh
  dipu/tests/cpp/CMakeLists.txt
  dipu/torch_dipu/csrc_dipu/CMakeLists.txt
Labels: bug, enhancement

#351 Make all in CMake
  dipu/scripts/ci/ascend/ci_ascend_script.sh
  dipu/scripts/ci/camb/ci_camb_script.sh
  dipu/scripts/ci/droplet/ci_droplet_script.sh
  dipu/scripts/ci/nv/ci_nv_script.sh
  dipu/scripts/ci/topsrider/ci_topsrider_script.sh
  dipu/setup.py
  dipu/torch_dipu/csrc_dipu/CMakeLists.txt
Labels: enhancement
